version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:17
    container_name: tickets-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-tickets}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-tickets}"]
      interval: 10s
      timeout: 5s
      retries: 5
    env_file:
      - .env

  # Nginx reverse proxy (dev) — proxies to host dev servers
  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    container_name: tickets-nginx
    ports:
      - "80:80"
    # Mount dev-specific nginx config that points to host.docker.internal
    volumes:
      - ./docker/nginx/nginx.dev.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - postgres

volumes:
  postgres_data:

networks:
  default:
    name: tickets-network
