@startuml
skinparam classAttributeIconSize 0
skinparam linetype polyline

abstract class Usuario {
  +id: UUID
  +nome: string
  +email: string
  +senhaHash: string
  +ultimoLogin: DateTime
}

class Passageiro {
  +cpf: string
  +telefone?: string
}

class Administrador {
  +cargo: string
  +ativo: boolean
}

class OrganizacaoResponsavel {
  +id: UUID
  +nome: string
  +cnpj: string
  +tipo: string
  +contatoPrincipal: string
}

abstract class Localizacao {
  +id: UUID
  +nome: string
  +descricao: string
  +endereco: string
  +latitude: decimal
  +longitude: decimal
}

class PontoOnibus {
  +codigoMunicipal: string
  +sentido: string
}

class EstacaoMetro {
  +linha: string
  +plataforma: string
  +acessibilidadeDisponivel: boolean
}

class TicketReporte {
  +id: UUID
  +titulo: string
  +descricao: string
  +dataCriacao: DateTime
  +dataFechamento?: DateTime
  +statusAtual: Status
  +gravidade: Gravidade
  +ultimaAtualizacao: DateTime
  +qtdConfirmacoes: int
}

class CategoriaProblema {
  +id: UUID
  +nome: string
  +descricao: string
  +exigeEvidencia: boolean
}

class Evidencia {
  +id: UUID
  +tipo: MediaTipo
  +url: string
  +tamanhoKB: int
}

class Comentario {
  +id: UUID
  +conteudo: string
  +dataCriacao: DateTime
  +privado: boolean
}

class HistoricoStatus {
  +id: UUID
  +dataHora: DateTime
  +statusAnterior: Status
  +statusAtual: Status
  +justificativa: string
}

class Notificacao {
  +id: UUID
  +mensagem: string
  +dataEnvio: DateTime
  +lida: boolean
  +canal: CanalNotificacao
}

Usuario <|-- Passageiro
Usuario <|-- Administrador

OrganizacaoResponsavel "1" -- "0..*" Administrador : emprega
OrganizacaoResponsavel "1" -- "0..*" Localizacao : mantém
Passageiro "1" -- "0..*" TicketReporte : cria
Administrador "1" -- "0..*" HistoricoStatus : registra
TicketReporte "1" -- "1" Localizacao : referencia
TicketReporte "1" -- "1" CategoriaProblema : classifica
TicketReporte "1" -- "0..*" Evidencia : agrega
TicketReporte "1" -- "0..*" Comentario : possui
TicketReporte "1" -- "0..*" HistoricoStatus : auditado por
Comentario "0..*" -- "1" Usuario : autor
Notificacao "0..*" -- "1" Usuario : destinatario

EstacaoMetro --|> Localizacao
PontoOnibus --|> Localizacao

enum Status {
  RASCUNHO
  AGUARDANDO_ANALISE
  REJEITADO
  ACEITO
  CORRECAO_EM_ANDAMENTO
  CORRIGIDO
  PAUSADO
  ARQUIVADO
}

enum Gravidade {
  BAIXA
  MEDIA
  ALTA
  CRITICA
}

enum MediaTipo {
  FOTO
  VIDEO
  AUDIO
  DOCUMENTO
}

enum CanalNotificacao {
  EMAIL
  PUSH
  SMS
}
@enduml